# -*- coding: utf-8 -*-
"""Quiz Game

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FJF6GKr6bUd9LQkUEVlVLIx7dhAscMSu
"""

print(" Welcome to the Python Quiz Game ")

name = input("Enter your name: ").strip()

score = 0

answer = input("1. Who is the present president in Sri Lanka ")
if answer.strip() == "Anura Kumara Dissanayake":
    score= score+ 1

answer = input("2. What is the capital of Sri Lanka ")
if answer.strip() == "Sri Jayawardanapura Kotte":
    score= score+ 1


answer = input("3. What is 5 + 3? ")
if answer.strip() == "8":
    score= score+ 1

answer = input("4. What does CPU stand for? ")
if answer.strip() == "Central Processing Unit":
    score= score+ 1
    
print("\nQuiz Completed!")
print(f"{name}, your final score is {score}/3")

if score == 3:
    print("Excellent!")
elif score == 2:
    print("Good job!")
elif score == 1:
    print("Keep practicing!")
else:
    print("Better luck next time!")
